# Port Metadata
PORTNAME =          miniaudio
PORTVERSION =       dev-0.12

MAINTAINER =        mackron
LICENSE =           Public Domain/MIT No Attribution
SHORT_DESC =        Audio playback and capture library written in C, in a single source file.

REQUIRES_ABI =      -m4-single

PORT_BUILD =        cmake

GIT_REPOSITORY =    https://github.com/mackron/miniaudio.git
GIT_BRANCH =        dev-0.12

TARGET =            libminiaudio.a
MAKE_TARGET =       miniaudio
INSTALLED_HDRS =    miniaudio.h

include ${KOS_PORTS}/scripts/kos-ports.mk