# Port Metadata
PORTNAME =          lftpd
PORTVERSION =       1.0.0

MAINTAINER =        Andy Barajas
LICENSE =           MIT
SHORT_DESC =        Small embeddable FTP server library

DEPENDENCIES =

# Upstream source.
GIT_REPOSITORIES =  https://github.com/Dreamcast-Projects/lftpd.git

TARGET =            liblftpd.a
INSTALLED_HDRS =    include/lftpd.h
HDR_INSTDIR =       lftpd

# KOS build file copied into the fetched source tree.
KOS_DISTFILES =     KOSMakefile.mk

include ${KOS_PORTS}/scripts/kos-ports.mk
